vendor/assets/stylesheets/styles.css

Modified vender/style.css for urls

css urls deleted

---

app/models/artist_genre.rb
app/models/artist_profile.rb
app/models/genre.rb
app/models/user.rb
app/models/venue_profile.rb
db/migrate/20220906104526_create_genres.rb
db/migrate/20220906125423_create_artist_profiles.rb
db/migrate/20220906130918_create_venue_profiles.rb
db/migrate/20220906131350_create_artist_genres.rb
spec/models/artist_genre_spec.rb
spec/models/artist_profile_spec.rb
spec/models/genre_spec.rb
spec/models/venue_profile_spec.rb

Tables initialization

---

app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb

Footer put back to the right place

footer replaced

---

app/views/layouts/_navbar.html.erb

Fixed link in navbar for disconnecting user

Creating navbar

---

app/views/layouts/_footer.html.erb
app/views/layouts/_navbar.html.erb

Links modified in footer and navbar (for root_path)

link in footer modified and link for root on navbar too

---

app/views/layouts/_navbar.html.erb

Modified "if" in html, "false" taken off

html modified: if without false

---

app/views/profile_selection/_show.html.erb

Links added to each profile creation

link added to each profile creation

---

app/views/artist_profiles/_edit.html.erb
app/views/artist_profiles/_show.html.erb
app/views/artist_profiles/edit.html.erb

page new done

---

app/views/devise/sessions/new.html.erb

margin bottom changed on log in page

---

app/views/layouts/_navbar.html.erb

link "mon profil" redirecting as intended

link modififed for profile

---

app/views/home/_banner.html.erb

Modifications home page

---

app/models/artist_profile.rb

add dependent destroy to artist profil model

dependences of artist_profile model updated

---

vendor/assets/stylesheets/styles.css

blanck line removed 3766

---

vendor/assets/stylesheets/styles.css

line 3766 removed

---

spec/views/profile_selection/show.html.erb_spec.rb

Update all spec because we need to log in before do test

Upddate view spec

---

app/controllers/application_controller.rb
app/controllers/artist_profiles_controller.rb
app/helpers/application_helper.rb
app/views/artist_profiles/_edit.html.erb
app/views/artist_profiles/_new.html.erb
app/views/artist_profiles/_show.html.erb
app/views/layouts/_flash.html.erb
app/views/layouts/application.html.erb
vendor/assets/stylesheets/styles.css

Controller method and partial for flash alert.
Front for artist profile new edit and show modified

Cleaning code artist

---

app/views/artist_profiles/_edit.html.erb

spelling back to profile link modified

spelling for artist profile edit

---

app/controllers/venue_profiles_controller.rb

venue controller dry

---

app/views/artist_profiles/_show.html.erb
app/views/venue_profiles/_show.html.erb

link modified for arstist and venue profile to redirect on the good index path

link for artist and venue profiles replaced

---

app/views/devise/sessions/new.html.erb
vendor/assets/stylesheets/styles.css

Add svg log in

---

README.md

Edit button

---

app/views/artist_profiles/_show.html.erb
app/views/venue_profiles/_show.html.erb

link for artist and venue show modified

link replaced

---

app/views/venue_profiles/_new.html.erb

Change word in view

---

app/views/artist_profiles/_show.html.erb

link working fine

---

app/views/artist_profiles/_index.html.erb
app/views/venue_profiles/_index.html.erb

pics added to index of artist and venue

pic added to index of artists and venues

---

config/storage.yml

missing S on acces pour heroku aws key

issing S in access key for aws heroku

---

app/views/artist_profiles/_show.html.erb
app/views/venue_profiles/_show.html.erb

button modified (btn class) for page artist and venue show

show artist and venue btn apply modified

---

app/views/artist_profiles/_index.html.erb
app/views/artist_profiles/_show.html.erb
app/views/dashboards/_artist.html.erb
app/views/venue_profiles/_index.html.erb
app/views/venue_profiles/_show.html.erb

pictures added for users who didn't upload one

Modif pages show

---

app/views/artist_profiles/_show.html.erb
app/views/performances/_show.html.erb
app/views/venue_profiles/_show.html.erb

link modified on performance show

link for pages of venues in performances modified

---

app/views/artist_profiles/_show.html.erb

link on artist profile for editing modified.

link modified for edit artist

---

app/views/applications/_show.html.erb

button_to link path modified

---

app/views/artist_profiles/_show.html.erb

resolve front bug when title of track is long

resolve front bug

---

app/controllers/performances_controller.rb
app/views/performances/_show.html.erb

button "booked" or "available" added for page show

Performance show button disableperf

---

app/views/home/_features.html.erb

Indented home features

---

app/controllers/application_controller.rb
app/controllers/performances_controller.rb
app/helpers/performances_helper.rb

added method preventing acces to performances index to others than artists profiles

Add method performance index

---

app/views/artist_profiles/_show.html.erb
app/views/dashboards/_artist.html.erb
app/views/dashboards/_venue.html.erb
app/views/performances/_show.html.erb
app/views/venue_profiles/_show.html.erb

buttons modified on dashboards and text description of show pages enlarged

buttons modified text on show larger
